### PR TITLE
Generate shortnames based on emojis-list

### PR DESCRIPTION
**Pull request by Kikobeats**
Related with https://github.com/Kikobeats/emojis-list/issues/10.

Can you confirm @astoilkov that this works as you expected?

### CODE REVIEW

**Comment by astoilkov** [comment]
I will try it out and get back to you today.

**Comment by astoilkov** [comment]
In the new list :octocat: `:octocat:` is missing.

**Comment by Kikobeats** [comment]
:octocat: is only available on GitHub I think.

**Comment by Kikobeats** [comment]
Both libraries content this emoji: http://twitter.github.io/twemoji/2/test/preview.html

**Pull request merged**
